version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: mcp-trino-postgres
    environment:
      POSTGRES_USER: trino
      POSTGRES_PASSWORD: trino
      POSTGRES_DB: trino
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trino-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trino"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: mcp-trino-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - trino-network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  # Trino Coordinator
  trino-coordinator:
    image: trinodb/trino:latest
    container_name: mcp-trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - trino-network
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/v1/info || exit 1
      interval: 7s
      timeout: 5s
      retries: 5

  # Metabase for visualization
  metabase:
    image: metabase/metabase:latest
    container_name: mcp-trino-metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=trino
      - MB_DB_PORT=5432
      - MB_DB_USER=trino
      - MB_DB_PASS=trino
      - MB_DB_HOST=mcp-trino-postgres
    networks:
      - trino-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  trino-network:
    driver: bridge

volumes:
  postgres-data:
  clickhouse-data:
